### ISSUE TITLE
Steam Authentication Error

### ISSUE THREAD

**Issue by JoelJoos** [VORPCORE/vorp_pre-made#10]
I recently set up a VORP RedM server using this repository. The Server runs just fine, however when I want to connect to it using RedM, I get the error "...you have to have Steam open..." & "... you are running Steam and it is signed in. ...". However, as the message suggests I have steam opened. Is it possible that there is a problem because I didn't buy the game on steam?

**Comment by AndrewR3K** [comment]
did you add your steam `steam_webApiKey `key to the `server.cfg`? 

This allows the game to steam auth properly.
[https://steamcommunity.com/dev/apikey](https://steamcommunity.com/dev/apikey)

**Comment by JoelJoos** [comment]
that solved it! thank you and sorry for bothering with my stupid question!
