### ISSUE TITLE
Can't import the SQL 

### ISSUE THREAD

**Issue by marksman717** [VORPCORE/vorp_pre-made#14]
Hello,

first off thanks for the amazing work!

i have set up your pre made server but for some reason i can't import the SQL into my database via phpmyadmin.. I get the error #1005 - Can't create table `redemrp`.`characters` (errno: 150 "Foreign key constraint is incorrectly formed")

would you have any ideas as to why?

**Comment by outsider31000** [comment]
this is not redmrp framework

**Comment by outsider31000** [comment]
theres alot of reasons why people dont use zap hosting. you will also need to change the path in your server.cfg never used zap hosting so cant really help you

**Comment by marksman717** [comment]
i'm starting to understand why we don't see videos for zap-hosting.. but thanks for your time!
 what host would you recommend?

**Comment by outsider31000** [comment]
you should use a vds or vps
