### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by Sneakey32** [VORPCORE/vorp_pre-made#15]
Hi, I'm new here but in the logs I see everything is working well but I have no "use" button in the inventory.

**Comment by RealStonerGamer** [comment]
its double click on the item now not a right click use 

 and this is not where to ask about this try the discord next time for help on this also issue with eash script should be in each repo not in the Premade Tx recipe
@Sneakey32

**Comment by RealStonerGamer** [comment]
vorp core discord : https://discord.gg/NzMNGduv

the vorp_Inventory repo: https://github.com/VORPCORE/vorp_inventory-lua

**Comment by Sneakey32** [comment]
Understood, thanks! I will have a look at the discord.
