### ISSUE TITLE
Menus in Spanish...

### ISSUE THREAD

**Issue by gkleinfe** [VORPCORE/vorp_pre-made#17]
I've checked the locale in the server.cfg and txadmin.  I've also issued a /locale command in game while connected to the server.  Alo option show en-US or English.  Some text is English, but the interaction menus in game are Spanish.  Where can I change that?

**Comment by AndrewR3K** [comment]
Some of these scripts were originally made in Spanish. There should be language configs or directions in most scripts within your resources folder.

**Comment by Domekologe** [comment]
I dont understand, when they made a "Pre Made" Server, why not every script will be setup in one language... this is only an "Half Pre Made"..

**Comment by outsider31000** [comment]
this isnt an issue
